In [7]:
my_fruit='ORANGE'
print(my_fruit)

myName="WIlliam"
print(myName)
mynumber=1228
mynuuuu=293092
mynumber+mynuuuu

ORANGE
WIlliam


294320

In [2]:
#funtion
def fune():
    name="John Smith"
    return(name)
    
fune()

'John Smith'

In [1]:
william ="sjksdjklsdjskd"
print( william)

sjksdjklsdjskd


In [ ]:
#class of car
class car:
    def __init__(self,make,model,color):
        self.make=make
        self.model=model
        self.color=color
        
    def

In [4]:
#This is sample of what I’ll be expecting:

class Car:
    def __init__(self, make, model, year, color, mileage):
        self.make = make
        self.model = model
        self.year = year
        self.color = color
        self.mileage = mileage
        
    def get_make_model(self):
        return f"{self.make} {self.model}"
    
    def get_age(self):
        return 2023 - self.year
    
    def get_color(self):
        return self.color
    
    def get_mileage(self):
        return self.mileage
    
    def add_mileage(self, additional_mileage):
        self.mileage += additional_mileage


    car1 = Car("Ford", "Mustang", 2018, "red", 45000.5)
    car2 = Car("Toyota", "Camry", 2021, "blue", 10000.2)
    car3 = Car("Honda", "Civic", 2015, "gray", 75000.9)

print(car1.get_make_model()) # output: Ford Mustang
print(car2.get_age()) # output: 2
print(car3.get_color()) # output: gray

car1.add_mileage(150.3)
print(car1.get_mileage()) # output: 45150.8

NameError: name 'Car' is not defined

In [5]:
friut=["banana","Apple","Pineapple"]
friut.append("Grape")

print(len(friut))
print(friut)
print(friut[0])

4
['banana', 'Apple', 'Pineapple', 'Grape']
banana


In [5]:
my_name="WIlliam Afoakwa "
print(my_name)
frist_name=my_name[0:7]
print(frist_name)
last_name=my_name[-8:-1]
print(last_name)

WIlliam Afoakwa 
WIlliam
Afoakwa


In [8]:
myName="Angelina Oduro"
myFirstName=myName[:8]
myLastName=myName[9:]
print(myFirstName)
print(myLastName)






Angelina
Oduro


In [1]:
Mine={"name":"John","age":4,"village":"Ekuase"}
Mine["name"] = "Angie","William"
Mine["programe"]="IT"
# Mine.values()
print(Mine)

{'name': ('Angie', 'William'), 'age': 4, 'village': 'Ekuase', 'programe': 'IT'}


In [3]:
my_dict={}
my_dict["first_name"]=input("What is your first name:")
print(my_dict)

What is your first name:willia
{'first_name': 'willia'}


In [4]:
my_book={}
my_book["name"]=input("Type your name:")
my_book["age"]=input("Type your age:")
my_book["year"]=input("Type your year:")

my_book

Type your name:wiloiam
Type your age:26
Type your year:292929


{'name': 'wiloiam', 'age': '26', 'year': '292929'}

In [8]:
#loops
ages=[22,19,12,30]
for age in ages:
    if age >15:
        print("You are eligible to vote")
    else:
        print("Sorry,your're eligible to vote")
        
print("hello")

You are eligible to vote
You are eligible to vote
Sorry,your're eligible to vote
You are eligible to vote
hello


type('

In [34]:
type('me')

str

In [36]:
'Ama'>'Joe'

False

In [38]:
'Joe'>'Ama'

True

In [2]:
chr(78)
2/3

0.6666666666666666

In [41]:
chr(45)
name="William Afoakwa"
first_name=name[0:8]
last_name 

'-'

In [1]:
#fibonaciii
fibonacii_list=[0,1]
fibonacii_limited=input("Enter the number of time it should run:\n")
for i in range(int(fibonacii_limited)):
    new_number=fibonacii_list[-2]+fibonacii_list[-1]
    fibonacii_list.append(new_number)

print(fibonacii_list)



#fibonaciii as function 
def fibonacii(n):
    number_list=[0,1]
    for i in range(int(n)):
        new_number=number_list[-2]+number_list[-1]
        number_list.append(new_number)
    return number_list

fibonacii(7)
#redo


Enter the number of time it should run:
3
[0, 1, 1, 2, 3]


[0, 1, 1, 2, 3, 5, 8, 13, 21]

In [77]:
#function
# sytax
# def funtionname(parameter):
 #       delcare a funtion

    
def greet(name="Alex"):
    print("Good afternoon",name)
    pass

greet("Agent 47")
#area of triangle
def area(base,height):
    return(0.5*base*height)
area(2,4)

#class
print(greet)
     

In [2]:
#class
name="william"
print(type(name))
name.upper()
name.lower()



<class 'str'>


'william'

In [ ]:
!pip install numpy

In [5]:
import numpy as np
import 

SyntaxError: invalid syntax (2773831787.py, line 2)

In [10]:
class Car:
    def __init__(self, make, model, year, color, mileage):
        self.make = make
        self.model = model
        self.year = year
        self.color = color
        self.mileage = mileage
        
    def get_make_model(self):
        return f"{self.make} {self.model}"
    
    def get_age(self):
        return 2023 - self.year
    
    def get_color(self):
        return self.color
    
    def get_mileage(self):
        return self.mileage
    
    def add_mileage(self, additional_mileage):
        self.mileage += additional_mileage


car1 = Car("Ford", "Mustang", 2018, "red", 45000.5)
car2 = Car("Toyota", "Camry", 2021, "blue", 10000.2)
car3 = Car("Honda", "Civic", 2015, "gray", 75000.9)

print(car1.get_make_model()) # output: Ford Mustang
print(car2.get_age()) # output: 2
print(car3.get_color()) # output: gray

car1.add_mileage(150.3)
print(car1.get_mileage()) # output: 45150.8


Ford Mustang
2
gray
45150.8


In [17]:
#numpy
import numpy as np
# arr=np.array([[1,2,4],[3,6,8],[7,9,0]])
# print(arr* 0.5)
# arw=np.array([[2,4],[7,0]])
# print(arw *2)
# #spq=np.sqrt()
ze=np.zeros(10,dtype=int).reshape(5,2)
#positonal argument and Keyword argument

print(ze)
on=np.ones(10,dtype=float).reshape(2,5)
print(on)



[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 0  5 10 15 20 25 30 35 40 45]


In [33]:
ii=np.arange(0,50,5).reshape(2,5)
np.sqrt(ii)



array([[0.        , 2.23606798, 3.16227766, 3.87298335, 4.47213595],
       [5.        , 5.47722558, 5.91607978, 6.32455532, 6.70820393]])

In [34]:
array = ii
array

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [35]:
np.mean(ii,axis=1)
#1=colim but provied the row mean
#2=row but provide the colum mean

array([10., 35.])

In [38]:
np.max(ii,axis=0)
#axis is bisa as barsa 


array([25, 30, 35, 40, 45])

In [39]:
!pip install pandas


Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     ---------------------------------------- 0.1/11.3 MB 1.7 MB/s eta 0:00:07
     ---------------------------------------- 0.1/11.3 MB 1.7 MB/s eta 0:00:07
     --------------------------------------- 0.1/11.3 MB 393.8 kB/s eta 0:00:29
     --------------------------------------- 0.1/11.3 MB 481.4 kB/s eta 0:00:24
      -------------------------------------- 0.2/11.3 MB 482.7 kB/s eta 0:00:24
      -------------------------------------- 0.2/11.3 MB 482.7 kB/s eta 0:00:24
      -------------------------------------- 0.2/11.3 MB 482.7 kB/s eta 0:00:24
      -------------------------------------- 0.2/11.3 MB 361.7 kB/s eta 0:00:31
      -------------------------------------- 0.2/11.3 MB 361.7 kB/s eta 0:00:31
      -------------------------------------- 0.2/11.3 MB 361.7 kB/s eta 0:00:31
      -------------------------------------- 0.2/11.


[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [43]:
import pandas as pd

In [44]:
data = pd.read_csv('country_wise_latest.csv')

In [45]:
data

Country/Region  Confirmed  Deaths  Recovered  Active  New cases   
0           Afghanistan      36263    1269      25198    9796        106  \
1               Albania       4880     144       2745    1991        117   
2               Algeria      27973    1163      18837    7973        616   
3               Andorra        907      52        803      52         10   
4                Angola        950      41        242     667         18   
..                  ...        ...     ...        ...     ...        ...   
182  West Bank and Gaza      10621      78       3752    6791        152   
183      Western Sahara         10       1          8       1          0   
184               Yemen       1691     483        833     375         10   
185              Zambia       4552     140       2815    1597         71   
186            Zimbabwe       2704      36        542    2126        192   

     New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases   
0            10             18                3.50                  69.49  \
1             6             63                2.95                  56.25   
2             8            749                4.16                  67.34   
3             0              0                5.73                  88.53   
4             1              0                4.32                  25.47   
..          ...            ...                 ...                    ...   
182           2              0                0.73                  35.33   
183           0              0               10.00                  80.00   
184           4             36               28.56                  49.26   
185           1            465                3.08                  61.84   
186           2             24                1.33                  20.04   

     Deaths / 100 Recovered  Confirmed last week  1 week change   
0                      5.04                35526            737  \
1                      5.25                 4171            709   
2                      6.17                23691           4282   
3                      6.48                  884             23   
4                     16.94                  749            201   
..                      ...                  ...            ...   
182                    2.08                 8916           1705   
183                   12.50                   10              0   
184                   57.98                 1619             72   
185                    4.97                 3326           1226   
186                    6.64                 1713            991   

     1 week % increase             WHO Region  
0                 2.07  Eastern Mediterranean  
1                17.00                 Europe  
2                18.07                 Africa  
3                 2.60                 Europe  
4                26.84                 Africa  
..                 ...                    ...  
182              19.12  Eastern Mediterranean  
183               0.00                 Africa  
184               4.45  Eastern Mediterranean  
185              36.86                 Africa  
186              57.85                 Africa  

[187 rows x 15 columns]

In [48]:
data.describe()

Confirmed         Deaths     Recovered        Active     New cases   
count  1.870000e+02     187.000000  1.870000e+02  1.870000e+02    187.000000  \
mean   8.813094e+04    3497.518717  5.063148e+04  3.400194e+04   1222.957219   
std    3.833187e+05   14100.002482  1.901882e+05  2.133262e+05   5710.374790   
min    1.000000e+01       0.000000  0.000000e+00  0.000000e+00      0.000000   
25%    1.114000e+03      18.500000  6.265000e+02  1.415000e+02      4.000000   
50%    5.059000e+03     108.000000  2.815000e+03  1.600000e+03     49.000000   
75%    4.046050e+04     734.000000  2.260600e+04  9.149000e+03    419.500000   
max    4.290259e+06  148011.000000  1.846641e+06  2.816444e+06  56336.000000   

        New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases   
count   187.000000     187.000000          187.000000             187.000000  \
mean     28.957219     933.812834            3.019519              64.820535   
std     120.037173    4197.719635            3.454302              26.287694   
min       0.000000       0.000000            0.000000               0.000000   
25%       0.000000       0.000000            0.945000              48.770000   
50%       1.000000      22.000000            2.150000              71.320000   
75%       6.000000     221.000000            3.875000              86.885000   
max    1076.000000   33728.000000           28.560000             100.000000   

       Deaths / 100 Recovered  Confirmed last week  1 week change   
count                  187.00         1.870000e+02     187.000000  \
mean                      inf         7.868248e+04    9448.459893   
std                       NaN         3.382737e+05   47491.127684   
min                      0.00         1.000000e+01     -47.000000   
25%                      1.45         1.051500e+03      49.000000   
50%                      3.62         5.020000e+03     432.000000   
75%                      6.44         3.708050e+04    3172.000000   
max                       inf         3.834677e+06  455582.000000   

       1 week % increase  
count         187.000000  
mean           13.606203  
std            24.509838  
min            -3.840000  
25%             2.775000  
50%             6.890000  
75%            16.855000  
max           226.320000